FROM node:18.10.0

WORKDIR /nodeapp
COPY ["../spa/", "./"]
RUN npm install --save-dev -g @angular/cli @angular-devkit/build-angular && npm install

ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 18

#install nvm with node and npm
RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash
RUN /bin/bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION && nvm alias default $NODE_VERSION && nvm use default"
COPY . /nodeapp

EXPOSE 4200
CMD npm start